const http = require('http'),
	express = require('express');

const TerraDiscordBot = require('./terra-discord-bot.js');

/**
 * A PhilibertApp is the main entry point of Philibert.
 */
var PhilibertApp = function PhilibertApp() {
	/**
	 * The Express server instance.
	 * @type {Express}
	 */
	this.app = express();

	/**
	 * The HTTP server instance generated by Express
	 * @type {HTTPServer}
	 */
	this.httpServer = this.app.listen(8080, () => {
		console.log('Philibert now running at 127.0.0.1:8080');
	});

	/**
	 * The Discord bot instance
	 * @type {TerraDiscordBot}
	 */
	this.discordBot = new TerraDiscordBot();

	// Method binding

	this.indexRoute = this.indexRoute.bind(this);
	this.handler404 = this.handler404.bind(this);
	this.close = this.close.bind(this);

	// Initialization

	this.app.get('/', this.indexRoute);
	this.app.use(this.handler404);

	this.httpServer.on('close', this.discordBot.logout);
};

/**
 * Display the homepage on a standard GET request
 * @param req Request data
 * @param res Response data
 */
PhilibertApp.prototype.indexRoute = function(req, res) {
	res.render('home.ejs');
};

/**
 * Display a 404 error code on erroneous requests
 * @param req Request data
 * @param res Response data
 * @param next
 */
PhilibertApp.prototype.handler404 = function(req, res, next) {
	res.setHeader('Content-Type', 'text/plain');
	res.status(404).send('Page not found');
};

/**
 * Gracefully close the app
 */
PhilibertApp.prototype.close = function() {
	this.httpServer.close();
};

// Initialization

var app = new PhilibertApp();
process.on('SIGINT', () => {
	console.log('Closing server');
	app.close();
});
